### ISSUE TITLE
Persistent Date in Azure is not possible

### ISSUE THREAD

**Issue by adisaljusi** [matomo-org/docker#201] opened 2020-06-03 12:45 UTC
Since February 2020, Azure does not support writable mounted storage. So everything is now read-only. Do you know if you can help out here? Both the official Matomo and the Bitnami image use volumes to store their data.

**Comment by J0WI** [comment] 2020-09-12 13:55
Closing as duplicate of https://github.com/matomo-org/docker/issues/177

**Closed by J0WI** 2020-09-12 13:55 UTC
