### ISSUE TITLE
piwik:3.0.3 Docker image seems to be v3.0.2

### ISSUE THREAD

**Issue by ginkel** [matomo-org/docker#60] opened 2017-04-09 18:01 UTC
Hello everyone,

after deploying the `piwik:3.0.3` Docker image I still get the Piwik update warning:

```
NEW UPDATE: PIWIK 3.0.3 Piwik 3.0.3 is available. 
Please update now! (see changes). 
You are currently using Piwik 3.0.2.
```

```
$ docker ps
CONTAINER ID      IMAGE           COMMAND                  CREATED              STATUS                       PORTS         NAMES 
07778e5f1069      piwik:3.0.3     "/entrypoint.sh ph..."   About a minute ago   Up About a minute            9000/tcp      piwik 
```

So, it seems as if the 3.0.3 Docker image actually contains Piwik 3.0.2.

Thanks,
Thilo

**Comment by mibruneel** [comment] 2017-04-09 21:13
@ginkel, you still have version 3.0.2 because Piwik code is stored in a volume. You need to manually delete the container and the volume, see issue #57.

**Comment by juliencarnot** [comment] 2018-04-26 12:42
duplicate of  #57, closing this.

**Closed by juliencarnot** 2018-04-26 12:42 UTC
