### ISSUE TITLE
Question: Skip wizard configuration and auto deploy capabilities

### ISSUE THREAD

**Issue by bouchezb** [matomo-org/docker#238] opened 2021-03-16 10:25 UTC
Hello,

I need to deploy Matomo via Docker on several servers.
At this point, i need to validate configuration via the setup wizard, but i want to by-pass this step and run configuration in an automated way, providing all necessary variables to Matomo (as if i full-filled the wizard form).

I can see there is an .ini file created, which is not a problem, but the creation of the database, it's population and evolution is more an issue to me.

Do you know if I can do this, and how ?

Regards.

**Comment by J0WI** [comment] 2021-03-24 22:28
Duplicate of https://github.com/matomo-org/matomo/issues/10257

**Closed by J0WI** 2021-03-24 22:28 UTC
